name: "house_prices_dbt"
version: "1.0.0"
config-version: 2

profile: house_prices

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  house_prices_dbt:
    +materialized: table

    staging:
      +schema: staging
      +materialized: table

    marts:
      +schema: marts
      +materialized: table