version: '3'
services:
  airflow:
    image: apache/airflow:2.8.0
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ../ml:/opt/airflow/project/ml
      - ../dbt:/opt/airflow/project/dbt
      - ../data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: webserver
